name: Deploy Helm Chart to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: reference-baton-426923-t0

      - name: Authenticate to GKE
        run: gcloud container clusters get-credentials reference-baton-426923-t0-gke --region us-east5

      - name: Install Helm
        run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Deploy with Helm
        run: |
          helm repo add fairwinds-stable https://charts.fairwinds.com/stable
          helm install my-goldilocks fairwinds-stable/goldilocks --version 8.0.2 -f values.yaml -f dev-values.yaml -n goldilocks
